import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import { cls } from "@/lib/utils";
import { motion } from "motion/react";

export default function AboutVisionWebPage() {
  return (
    <>
      <div data-webild-section="AboutText"><section aria-label="About section" className="py-20"><div className="w-content-width mx-auto flex flex-col gap-2 items-center"><TextAnimation text="We Build Websites That Move as Fast as Your Business." variant="fade-blur" gradientText={false} tag="h2" className="text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance" /><div className="flex flex-wrap gap-3 justify-center mt-2 md:mt-3"><Button text="Book Consultation" href="/contact" variant="primary" /><Button text="View Our Work" href="/portfolio" variant="secondary" animationDelay={0.1} /></div></div></section></div>
      <div data-webild-section="AboutTextSplit"><section aria-label="About section" className="py-20"><div className="flex flex-col gap-20 mx-auto w-content-width"><div className="flex flex-col md:flex-row gap-3 md:gap-15"><div className="w-full md:w-1/2"><TextAnimation text="About VisionWeb" variant="slide-up" gradientText={true} tag="h2" className="text-7xl 2xl:text-8xl leading-[1.15] font-semibold text-balance" /></div><div className="flex flex-col gap-2 w-full md:w-1/2"><TextAnimation key={0} text="At VisionWeb, we believe a great website shouldn't take weeks to launch. We combine modern design with a streamlined process to deliver high-converting sites in just 24 hours." variant="slide-up" gradientText={false} tag="p" className="text-xl md:text-2xl leading-snug text-balance" />
<TextAnimation key={1} text="VisionWeb was founded because businesses shouldn't wait a month or pay a fortune to get online. We replaced slow, overcomplicated traditional web design with an efficient process." variant="slide-up" gradientText={false} tag="p" className="text-xl md:text-2xl leading-snug text-balance" />
<TextAnimation key={2} text="Our mission is to help local businesses and entrepreneurs establish a powerful online presence quickly, affordably, and without the usual headaches." variant="slide-up" gradientText={false} tag="p" className="text-xl md:text-2xl leading-snug text-balance" />
<TextAnimation key={3} text="We stand out by offering 24-hour delivery, conversion-focused design, and personal service. Every website is crafted to fit your brand and generate real results." variant="slide-up" gradientText={false} tag="p" className="text-xl md:text-2xl leading-snug text-balance" /><div className="flex flex-wrap gap-3 mt-2 md:mt-3"><Button text="Book Consultation" href="/contact" variant="primary" /><Button text="View Our Work" href="/portfolio" variant="secondary" animationDelay={0.1} /></div></div></div><div className="w-full border-b border-foreground/5" /></div></section></div>
      <div data-webild-section="FeaturesBentoGrid"><section aria-label="Features section" className="py-20"><div className="flex flex-col gap-8 md:gap-10"><div className="flex flex-col items-center gap-2 w-content-width mx-auto"><div className="px-3 py-1 mb-1 text-sm card rounded w-fit"><p>Our Difference</p></div><TextAnimation text="Websites That Move as Fast as Your Business" variant="fade-blur" gradientText={true} tag="h2" className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance" /><TextAnimation text="We combine modern design with a streamlined development process to deliver professional, high-converting websites in as little as 24 hours." variant="fade-blur" gradientText={false} tag="p" className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance" /><div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3"><Button text="Book Consultation" href="#contact" variant="primary" /><Button text="View Our Work" href="#portfolio" variant="secondary" animationDelay={0.1} /></div></div><ScrollReveal variant="fade-blur" className="w-content-width mx-auto"><div className="grid grid-cols-1 md:grid-cols-12 gap-5"><div key="24-Hour Delivery" className="md:col-span-5 flex flex-col gap-3 xl:gap-3.5 2xl:gap-4 p-3 xl:p-3.5 2xl:p-4 card rounded"><div className="h-60 xl:h-72 2xl:h-80 rounded overflow-hidden bg-foreground/5 shadow shadow-foreground/5"><ImageOrVideo imageSrc="https://img.freepik.com/free-photo/fast-speed-internet-connection-technology-concept_53876-124742.jpg" /></div><div className="flex flex-col gap-1 p-3 xl:p-3.5 2xl:p-4"><h3 className="text-2xl font-semibold leading-snug text-balance">24-Hour Delivery</h3><p className="text-base leading-snug text-balance">Our streamlined process means you can go from idea to live website in just one day.</p></div></div>
<div key="Built to Convert" className="md:col-span-7 flex flex-col gap-3 xl:gap-3.5 2xl:gap-4 p-3 xl:p-3.5 2xl:p-4 card rounded"><div className="h-60 xl:h-72 2xl:h-80 rounded overflow-hidden bg-foreground/5 shadow shadow-foreground/5"><ImageOrVideo imageSrc="https://img.freepik.com/free-photo/business-people-analyzing-statistics-financial-data_53876-13796.jpg" /></div><div className="flex flex-col gap-1 p-3 xl:p-3.5 2xl:p-4"><h3 className="text-2xl font-semibold leading-snug text-balance">Built to Convert</h3><p className="text-base leading-snug text-balance">We design your online presence specifically to generate leads, bookings, and sales for your business.</p></div></div>
<div key="Personal & Responsive" className="md:col-span-7 flex flex-col gap-3 xl:gap-3.5 2xl:gap-4 p-3 xl:p-3.5 2xl:p-4 card rounded"><div className="h-60 xl:h-72 2xl:h-80 rounded overflow-hidden bg-foreground/5 shadow shadow-foreground/5"><ImageOrVideo imageSrc="https://img.freepik.com/free-photo/smiling-businesswoman-talking-phone-office_107420-20993.jpg" /></div><div className="flex flex-col gap-1 p-3 xl:p-3.5 2xl:p-4"><h3 className="text-2xl font-semibold leading-snug text-balance">Personal & Responsive</h3><p className="text-base leading-snug text-balance">We work closely with every client to understand their unique goals and bring their vision to life.</p></div></div>
<div key="Expertise You Can Trust" className="md:col-span-5 flex flex-col gap-3 xl:gap-3.5 2xl:gap-4 p-3 xl:p-3.5 2xl:p-4 card rounded"><div className="h-60 xl:h-72 2xl:h-80 rounded overflow-hidden bg-foreground/5 shadow shadow-foreground/5"><ImageOrVideo imageSrc="https://img.freepik.com/free-photo/web-design-concept-with-drawings_1134-77.jpg" /></div><div className="flex flex-col gap-1 p-3 xl:p-3.5 2xl:p-4"><h3 className="text-2xl font-semibold leading-snug text-balance">Expertise You Can Trust</h3><p className="text-base leading-snug text-balance">Every website is crafted and refined by our team to ensure it truly fits your brand.</p></div></div></div></ScrollReveal></div></section></div>
      <div data-webild-section="AboutMediaOverlay"><section aria-label="About section" className="py-20"><div className="relative flex items-center justify-center py-8 md:py-12 mx-auto w-content-width rounded overflow-hidden"><div className="absolute inset-0"><ImageOrVideo imageSrc="https://img.freepik.com/free-photo/business-people-working-together-office_107420-84841.jpg" /><div className="absolute inset-0 bg-foreground/40 backdrop-blur-xs pointer-events-none select-none" /></div><div className="relative z-10 flex items-center justify-center px-5 py-10 mx-auto min-h-100 md:min-h-120 md:w-1/2 w-content-width"><div className="flex flex-col items-center gap-2 text-center"><motion.span initial={{"opacity":0,"y":10}} whileInView={{"opacity":1,"y":0}} viewport={{"once":true,"margin":"-15%"}} transition={{"duration":0.4,"ease":"easeOut"}} className="mb-1 px-3 py-1 text-sm card rounded">About VisionWeb</motion.span><TextAnimation text="Websites That Move as Fast as Your Business" variant="slide-up" gradientText={true} tag="h2" className="text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-balance text-primary-cta-text" /><TextAnimation text="We combine modern design with a streamlined process to deliver professional, high-converting websites in as little as 24 hours—without cutting corners." variant="slide-up" gradientText={false} tag="p" className="text-lg md:text-xl leading-snug text-balance text-primary-cta-text" /><div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3"><Button text="Get Started" href="/contact" variant="primary" /><Button text="Our Story" href="#our-story" variant="secondary" animationDelay={0.1} /></div></div></div></div></section></div>
      <div data-webild-section="ContactCta"><section aria-label="Contact section" className="py-20"><div className="w-content-width mx-auto"><ScrollReveal variant="slide-up"><div className="flex flex-col items-center gap-8 md:gap-10 py-20 px-8 rounded card"><div className="flex flex-col items-center gap-2"><div className="px-3 py-1 mb-1 text-sm card rounded w-fit"><p>Ready to Get Started?</p></div><TextAnimation text="Let's build something great together. Book a free consultation today and see your new website live within 24 hours." variant="slide-up" gradientText={true} tag="h2" className="md:max-w-8/10 text-5xl 2xl:text-6xl leading-[1.15] font-semibold text-center text-balance" /><div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3"><Button text="Book Consultation" href="/contact" variant="primary" /><Button text="View Our Work" href="/portfolio" variant="secondary" animationDelay={0.1} /></div></div></div></ScrollReveal></div></section></div>
    </>
  );
}
