// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Get Started"
          text="Ready to build your digital future? Let's discuss your next project."
          primaryButton={{
            text: "Book a Consultation",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Email Us",
            href: "mailto:hello@visionweb.agency",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
