// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTwoColumn from '@/components/sections/faq/FaqTwoColumn';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTwoColumn
          tag="FAQ"
          title="Frequently Asked Questions"
          description="Answers to the common questions our clients ask during the onboarding process."
          items={[
            {
              question: "What is your typical project timeline?",
              answer: "Our process is built for speed: your professional website ready in as little as 24 hours. Perfect if you're on a tight deadline and need to launch fast.",
            },
            {
              question: "Do you offer ongoing support?",
              answer: "Yes, we provide flexible monthly maintenance and growth partnerships.",
            },
            {
              question: "How do you handle pricing?",
              answer: "We provide transparent, fixed-price proposals based on scope and deliverables.",
            },
            {
              question: "What industries do you serve?",
              answer: "We focus on technology, professional services, and high-growth  brands.",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
