// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsSimpleCards
          tag="Performance"
          title="Impact by the Numbers"
          description="Our work is measured by the tangible improvements in business performance."
          metrics={[
            {
              value: "100+",
              description: "Successful projects launched",
            },
            {
              value: "200%",
              description: "Average conversion lift",
            },
            {
              value: "45%",
              description: "Reduced customer acquisition costs",
            },
            {
              value: "95%",
              description: "Client retention rate",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
