// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesBorderGlow from '@/components/sections/features/FeaturesBorderGlow';
import { Code, Layout, Target } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesBorderGlow
          tag="Our Expertise"
          title="Comprehensive Digital Solutions"
          description="We blend creativity with technical excellence to build powerful web solutions that accelerate growth."
          features={[
            {
              icon: Layout,
              title: "Web twitter",
              description: "Crafting intuitive and aesthetically pleasing digital experiences that resonate with your target users.",
            },
            {
              icon: Code,
              title: "Web instagram",
              description: "High-performance code built for scalability, security, and exceptional user experience on every device.",
            },
            {
              icon: Target,
              title: "Digital Strategy",
              description: "Data-backed planning to ensure your website directly contributes to business objectives and ROI.",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
