// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "showcase" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ShowcaseSection(): React.JSX.Element {
  return (
    <div id="showcase" data-section="showcase">
        <SectionErrorBoundary name="showcase">
              <FeaturesRevealCardsBento
          tag="Portfolio"
          title="Projects That Drive Results"
          description="Explore how we've helped SMBs scale through design-led innovation."
          items={[
            {
              title: "Tech Platform Redesign",
              description: "Increased lead generation by 45%.",
              href: "#contact",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G2Ozqag2ovb8not76KWtboL8LU/uploaded-1783255601315-tyfwj7vc.jpg",
            },
            {
              title: "E-commerce Optimization",
              description: "Reduced bounce rates by 30%.",
              href: "#contact",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G2Ozqag2ovb8not76KWtboL8LU/uploaded-1783255759459-l81ogd47.jpg",
            },
            {
              title: "Global SaaS Dashboard",
              description: "Streamlined user workflows significantly.",
              href: "#contact",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G2Ozqag2ovb8not76KWtboL8LU/uploaded-1783254527878-2ywgjatp.jpg",
            },
            {
              title: "Brand Identity Refresh",
              description: "Modernizing a legacy company brand.",
              href: "#contact",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G2Ozqag2ovb8not76KWtboL8LU/uploaded-1783254756485-d4h2evy9.jpg",
            },
            {
              title: "Interactive Content Hub",
              description: "Driving audience engagement.",
              href: "#contact",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G2Ozqag2ovb8not76KWtboL8LU/uploaded-1783255273266-raq380ge.jpg",
            },
            {
              title: "B2B Lead Portal",
              description: "Optimized lead capture funnels.",
              href: "#contact",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G2Ozqag2ovb8not76KWtboL8LU/uploaded-1783255387966-yjpuemk1.jpg",
            },
            {
              title: "Custom App Interface",
              description: "Intuitive mobile application design.",
              href: "#contact",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G2Ozqag2ovb8not76KWtboL8LU/uploaded-1783255465326-16ekbrta.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
