// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "showcase" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ShowcaseSection(): React.JSX.Element {
  return (
    <div id="showcase" data-section="showcase">
        <SectionErrorBoundary name="showcase">
              <FeaturesRevealCardsBento
          tag="Portfolio"
          title="Projects That Drive Results"
          description="Explore how we've helped SMBs scale through design-led innovation."
          items={[
            {
              title: "Tech Platform Redesign",
              description: "Increased lead generation by 45%.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/still-life-graphic-design-office_23-2151345406.jpg",
            },
            {
              title: "E-commerce Optimization",
              description: "Reduced bounce rates by 30%.",
              href: "#contact",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3G2Ozqag2ovb8not76KWtboL8LU/uploaded-1783251235920-e8chdzpa.jpg",
            },
            {
              title: "Global SaaS Dashboard",
              description: "Streamlined user workflows significantly.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/global-business-strategy-planning-icon-concept_53876-120444.jpg",
            },
            {
              title: "Brand Identity Refresh",
              description: "Modernizing a legacy company brand.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-vector/20-digital-marketing-solid-glyph-icon-presentation-vector-icons-illustration_1142-17871.jpg",
            },
            {
              title: "Interactive Content Hub",
              description: "Driving audience engagement.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/modern-smartphone-with-blank-screen-studio_187299-46431.jpg",
            },
            {
              title: "B2B Lead Portal",
              description: "Optimized lead capture funnels.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/support-consulting-help-graphic-icon-word_53876-124360.jpg",
            },
            {
              title: "Custom App Interface",
              description: "Intuitive mobile application design.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/globe-internet-icon-line-connection-circuit-board_1379-893.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
