// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamOverlayCards from '@/components/sections/team/TeamOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
        <SectionErrorBoundary name="team">
              <TeamOverlayCards
        tag="The Visionaries"
        title="Meet the Team Behind Your Results"
        description="We are a tight-knit team of strategists, designers, and developers dedicated to your success."
        members={[{"role":"Creative Director","imageSrc":"https://storage.googleapis.com/webild/users/user_3G2Ozqag2ovb8not76KWtboL8LU/uploaded-1783172117883-w602ocjj.png","name":"Yahya Sahraoui"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3G2Ozqag2ovb8not76KWtboL8LU/uploaded-1783172630842-tmba3pi4.png","name":"Nader Amri","role":"Lead Developer"}]}
        textAnimation="fade-blur"
      />
        </SectionErrorBoundary>
      </div>
  );
}