// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
          tag="Social Proof"
          title="Trusted by Growing Businesses"
          description="Hear what our clients have to say about the impact VisionWeb has made on their organizations."
          testimonials={[
            {
              name: "Alex Rivers",
              role: "CEO, Rivers Tech",
              quote: "VisionWeb transformed our digital presence. We saw immediate ROI after the redesign.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-smiley-business-woman_23-2148603029.jpg",
            },
            {
              name: "Maria Garcia",
              role: "Marketing VP, Sol Solutions",
              quote: "Their strategic approach is unique. They don't just build websites; they build businesses.",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-competitive-employee_1098-2870.jpg",
            },
            {
              name: "John Doe",
              role: "Founder, CloudPeak",
              quote: "The development team is top-tier. Extremely professional and communicative throughout the process.",
              imageSrc: "http://img.b2bpic.net/free-photo/successful-business-people-with-announcement_53876-15202.jpg",
            },
            {
              name: "Sarah L.",
              role: "CMO, GrowthSpurt",
              quote: "VisionWeb is our long-term partner for everything digital.",
              imageSrc: "http://img.b2bpic.net/free-photo/lady-grey-suit-smiling-camera-background-stylish-cafe-with-lights_291650-637.jpg",
            },
            {
              name: "Tom Baker",
              role: "Founder",
              quote: "The conversion results exceeded our expectations by far.",
              imageSrc: "http://img.b2bpic.net/free-photo/positive-hipster-entrepreneur-it-expert-software-developer_74855-3635.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
